In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [48]:
dataset= pd.read_csv('Startups.csv')
X= dataset.iloc[:,0:3].values
Y= dataset.iloc[:,4].values

In [42]:
#print(X)

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size= 1/10)

In [37]:
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [46]:
Y_pred= regressor.predict(X_test)

In [49]:
print(X_test)
print(Y_pred)

[[ 77044.01  99281.34 140574.81]
 [119943.24 156547.42 256512.92]
 [101913.08 110594.11 229160.95]
 [ 63408.86 129219.61  46085.25]
 [100671.96  91790.61 249744.55]]
[112885.07511808 150449.18945967 135284.98042319  99284.56635857
 134882.67042185]
